sections:
  - title: Major changes
    labels:
      - "release/super-feature"
  - title: Complete changelog
    labels:
      - "bug"
      - "enhancement"
      - "dependencies"
template: |
  {{ range $section := .Sections }}{{ if $section.Items }}### {{ $section.GetTitle }}{{ range $item := $section.Items }}
  * [#{{ $item.GetID }}]({{ $item.GetURL }}) - {{ $item.GetTitle }}{{ end }}{{ end }}
  {{ end }}