---
openapi: 3.0.3
info:
  title: onecx-workspace data import workspace
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/workspace:
    post:
      operationId: importWorkspace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceDataImport'
      responses:
        200:
          description: ok
components:
  schemas:
    WorkspaceDataImport:
      type: object
      properties:
        requests:
          type: array
          items:
            $ref: '#/components/schemas/ImportRequest'
    ImportRequest:
      required:
        - workspace
      type: object
      properties:
        tenantId:
          description: tenant id
          type: string
        workspace:
          $ref: '#/components/schemas/WorkspaceImport'
        menuItems:
          description: Menu Items structure imported with a workspace
          type: array
          items:
            $ref: '#/components/schemas/MenuItemStructure'
    MenuItemStructure:
      type: object
      properties:
        key:
          type: string
        name:
          type: string
        description:
          type: string
        url:
          type: string
        disabled:
          type: boolean
        position:
          format: int32
          type: integer
        external:
          type: boolean
        i18n:
          type: object
          additionalProperties:
            type: string
        roles:
          type: array
          uniqueItems: true
          items:
            type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/MenuItemStructure'
    WorkspaceImport:
      description: Workspace data to be imported
      required:
        - name
      type: object
      properties:
        name:
          description: Name of the workspace that should be created/updated
          minLength: 1
          type: string
        themeName:
          description: Theme name provided in a case when themeImportData is empty
          type: string
        description:
          type: string
        homePage:
          type: string
        baseUrl:
          type: string
        companyName:
          type: string
        address:
          $ref: '#/components/schemas/WorkspaceAddress'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceRole'
        phoneNumber:
          type: string
        rssFeedUrl:
          type: string
        footerLabel:
          type: string
        products:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Product"
        workspaceRoles:
          type: array
          uniqueItems: true
          items:
            type: string
        logoUrl:
          type: string
    SubjectLink:
      type: object
      properties:
        label:
          type: string
        url:
          type: string
    WorkspaceRole:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    WorkspaceAddress:
      type: object
      properties:
        street:
          type: string
        streetNo:
          type: string
        city:
          type: string
        country:
          type: string
        postalCode:
          type: string
    Product:
      description: "Product to be imported"
      type: object
      properties:
        productName:
          type: string
        baseUrl:
          type: string
        microfrontends:
          type: array
          items:
            $ref: '#/components/schemas/Microfrontend'
    Microfrontend:
      description: "MFE defined under product for a path inside of the product"
      type: object
      properties:
        mfeId:
          type: string
        basePath:
          type: string