---
openapi: 3.0.3
info:
  title: onecx-workspace external service V1
  description: This API provides endpoints to retrieve Workspaces
  version: 1.0.0
servers:
  - url: "http://onecx-workspace:8080"
tags:
  - name: workspaceExternal
    description: Retrieve Workspaces
paths:
  /v1/workspaces/byUrl:
    post:
      security:
        - oauth2: [ ocx-ws:read ]
      tags:
        - workspaceExternal
      description: Search workspace by its url
      operationId: getWorkspaceByUrl
      deprecated: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetWorkspaceByUrlRequest'
      responses:
        "200":
          description: Workspace retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
        "404":
          description: Workspace not found
  /v1/workspaces/load:
    post:
      security:
        - oauth2: [ ocx-ws:read ]
      tags:
        - workspaceExternal
      description: Load workspace by request
      operationId: loadWorkspaceByRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceLoadRequest'
      responses:
        "200":
          description: Workspace retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceWrapper'
        "404":
          description: Workspace not found
  /v1/workspaces/search:
    post:
      security:
        - oauth2: [ ocx-ws:read ]
      tags:
        - workspaceExternal
      description: Search workspace abstracts by search criteria
      operationId: searchWorkspaces
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceSearchCriteria'
      responses:
        "200":
          description: Workspace retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspacePageResult'
  /v1/workspaces/{name}:
    get:
      security:
        - oauth2: [ ocx-ws:read ]
      tags:
        - workspaceExternal
      description: Get a workspace by its name
      operationId: getWorkspaceByName
      parameters:
        - $ref: '#/components/parameters/name'
      responses:
        "200":
          description: Workspace retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workspace'
  /v1/workspaces/{name}/load:
    get:
      security:
        - oauth2: [ ocx-ws:read ]
      tags:
        - workspaceExternal
      description: Load workspace products by its name
      operationId: loadWorkspaceByName
      parameters:
        - $ref: '#/components/parameters/name'
      responses:
        "200":
          description: Workspace products retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceLoad'
        "404":
          description: Workspace not found
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-ws:read: Grants read access
            ocx-ws:write: Grants write access
            ocx-ws:delete: Grants access to delete operations
  schemas:
    WorkspaceWrapper:
      type: object
      properties:
        name:
          type: string
        displayName:
          type: string
        baseUrl:
          type: string
        homePage:
          type: string
        theme:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        slots:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceWrapperSlot'
    WorkspaceWrapperSlot:
      type: object
      properties:
        name:
          type: string
        components:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceWrapperComponent'
    WorkspaceWrapperComponent:
      type: object
      properties:
        productName:
          type: string
        appId:
          type: string
        name:
          type: string
    WorkspaceLoad:
      type: object
      properties:
        name:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Workspace:
      required:
        - name
      type: object
      properties:
        name:
          type: string
        displayName:
          type: string
        description:
          type: string
        theme:
          type: string
        homePage:
          type: string
        baseUrl:
          type: string
        companyName:
          type: string
        phoneNumber:
          type: string
        rssFeedUrl:
          type: string
        footerLabel:
          type: string
        disabled:
          type: boolean
        workspaceRoles:
          type: array
          uniqueItems: true
          items:
            type: string
        logoUrl:
          type: string
        products:
          type: array
          uniqueItems: true
          items:
            type: string
        address:
          $ref: '#/components/schemas/WorkspaceAddress'
    WorkspaceAddress:
      type: object
      properties:
        street:
          type: string
        streetNo:
          type: string
        city:
          type: string
        country:
          type: string
        postalCode:
          type: string
    WorkspacePageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceAbstract'
    WorkspaceAbstract:
      type: object
      properties:
        name:
          type: string
        displayName:
          type: string
        disabled:
          type: boolean
        theme:
          type: string
        description:
          type: string
    WorkspaceSearchCriteria:
      type: object
      properties:
        themeName:
          type: string
        productName:
          type: string
        workspaceName:
            type: string
        baseUrl:
          type: string
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    Product:
      type: object
      properties:
        productName:
          type: string
        displayName:
          type: string
        baseUrl:
          type: string
        microfrontends:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Microfrontend'
    Microfrontend:
      type: object
      properties:
        mfeId:
          type: string
        basePath:
          type: string
    WorkspaceLoadRequest:
      type: object
      required:
        - path
      properties:
        path:
          type: string
    GetWorkspaceByUrlRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
  parameters:
    name:
      in: path
      name: name
      required: true
      schema:
        type: string
