---
openapi: 3.0.3
info:
  title: onecx-portal legacy service
  version: 1.0.0
servers:
  - url: "http://onecx-portal:8080"
tags:
  - name: V1MenuStructure
  - name: V2MenuStructure
paths:
  /1000kit-portal-server/menustructure/{portalId}/{appId}:
    get:
      tags:
        - V1MenuStructure
      description: Fetch the menuItems of the portal and application pair in the tree
        structure
      operationId: getMenuStructureForPortalIdAndApplicationId
      parameters:
        - name: appId
          in: path
          required: true
          schema:
            type: string
        - name: portalId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
        "401":
          description: Not authorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
    post:
      tags:
        - V1MenuStructure
      description: Register menu from the application
      operationId: submitMenuRegistrationRequest
      parameters:
        - name: portalId
          in: path
          required: true
          schema:
            type: string
        - name: appId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuRegistrationRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuRegistrationResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
      deprecated: true
  /1000kit-portal-server/menustructure/{portalId}:
    get:
      tags:
        - V1MenuStructure
      description: Fetch the menuItems of the portal in the tree structure
      operationId: getMenuStructureForPortalId
      parameters:
        - name: portalId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
        "401":
          description: Not authorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
      deprecated: true
  /1000kit-portal-server/v2/menustructure/{portalId}:
    get:
      tags:
        - V2MenuStructure
      description: Fetch the menuItems of the portal in the tree structure
      operationId: getMenuStructureV2ForPortalId
      parameters:
        - name: portalId
          in: path
          required: true
          schema:
            type: string
        - name: interpolate
          in: query
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
        "401":
          description: Not authorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
      deprecated: true
components:
  schemas:
    RestException:
      type: object
      properties:
        code:
          type: string
        codeClass:
          type: string
        message:
          type: string
        parameters:
          type: array
          items:
            type: object
        namedParameters:
          type: object
          additionalProperties:
            type: object
    MenuItem:
      type: object
      properties:
        persisted:
          type: boolean
        guid:
          type: string
        version:
          format: int32
          type: integer
        key:
          type: string
        name:
          type: string
        i18n:
          type: object
          additionalProperties:
            type: string
        url:
          type: string
        portalId:
          type: string
        disabled:
          type: boolean
        position:
          format: int32
          type: integer
        children:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'
        permissionObject:
          type: string
        badge:
          type: string
        scope:
          $ref: '#/components/schemas/Scope'
        applicationId:
          type: string
        portalExit:
          type: boolean
        parentKey:
          type: string
    Scope:
      enum:
        - PORTAL
        - APP
        - PAGE
      type: string
    MenuRegistrationRequest:
      type: object
      properties:
        requestVersion:
          type: integer
        menuItems:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'
    MenuRegistrationResponse:
      type: object
      properties:
        applicationId:
          type: string
        requestVersion:
          type: integer
        applied:
          type: boolean
        notice:
          type: string
