---
openapi: 3.0.3
info:
  title: onecx-portal operator service
  version: 1.0.0
servers:
  - url: "http://onecx-portal:8080"
tags:
  - name: operator
paths:
  /operator/v1/microfrontends/{id}:
     put:
      tags:
        - operator
      description: Creates or updates a microfrontend registration.
      operationId: updateMicrofrontend
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMicrofrontendRegistration'
      responses:
        "201":
          description: Create new micro-frontend
          headers:
            Location:
              required: true
              schema:
                type: string
                format: url
        "204":
          description: Update existing micro-frontend
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
components:
  schemas:
    RestException:
       type: object
       properties:
         errorCode:
           type: string
         message:
           type: string
         parameters:
           type: array
           items:
             type: object
         namedParameters:
           type: object
           additionalProperties:
             type: object
         validations:
           type: array
           items:
             $ref: '#/components/schemas/ValidationConstraint'
    ValidationConstraint:
      type: object
      properties:
        parameter:
          type: string
        message:
          type: string
    UpdateMicrofrontendRegistration:
       required:
         - remoteEntry
         - remoteName
         - exposedModule
         - displayName
         - moduleType
         - remoteBaseUrl
       type: object
       properties:
         remoteEntry:
           minLength: 2
           type: string
         remoteName:
           minLength: 2
           type: string
         exposedModule:
           minLength: 2
           type: string
         displayName:
           minLength: 2
           type: string
         moduleType:
           $ref: '#/components/schemas/ModuleType'
         wcTagName:
           type: string
         appId:
           type: string
         appVersion:
           type: string
         note:
           type: string
         contact:
           type: string
         remoteBaseUrl:
           minLength: 2
           type: string
    ModuleType:
      enum:
        - ANGULAR
        - WEBCOMPONENT
      type: string